= Personalized PageRank

.Supported Graph Characteristics
****
[cols='1']
|===
^|Unweighted edges
^|Directed edges
^|Homogeneous vertex types
^|Heterogeneous vertex types
|===

[NOTE]
Use the Degree Centrality algorithm on an undirected graph instead of Personalized PageRank.

****


In the original PageRank, the damping factor is the probability of the surfer continues browsing at each step. The surfer may also stop browsing and start again from a random vertex. In personalized PageRank, the surfer can only start browsing from a given set of source vertices both at the beginning and after stopping.

== Specifications

[source,gsql]
----
tg_pagerank_pers(SET<VERTEX> source, STRING e_type,
FLOAT max_change=0.001, INT max_iter=25, FLOAT damping = 0.85, INT top_k = 100
BOOL print_accum = TRUE, STRING result_attr = "", STRING file_path = "")
----

== Example

We ran Personalized PageRank on the graph `social10` using Friend edges with the following parameter values:

[source,gsql]
----
# Using "_" to use default values
RUN QUERY tg_pagerank_pers([("Fiona","Person")], "Friend", _, _, _, _, _, _,
_)
----

In this case, the random walker can only start or restart walking from Fiona. In the figure below, we see that Fiona has the highest PageRank score in the result. Ivy and George have the next highest scores because they are direct out-neighbors of Ivy and there are looping paths that lead back to them again. Half of the vertices have a score of 0 since they can not be reached from Fiona.

image::screen-shot-2019-04-25-at-4.09.01-pm (1).png[ Visualized results of example query on social10 graph, with Friend edges]

###
