= TigerGraph Graph Data Science Library
:page-aliases: intro:overview.adoc

TigerGraph In-Database Graph Data Science (GDS) Library is a collection of more than 50 expertly written, ready-to-use GSQL queries, each of which implements a standard graph or machine learning algorithm.

GSQL running on the TigerGraph platform is particularly well-suited for graph algorithms for several reasons:

* *Turing-complete* with full support for imperative and procedural programming, ideal for algorithmic computation.
* *Parallel and Distributed Processing,* enabling computations on larger graphs.
* *User-Extensible*. Because the algorithms are written in standard GSQL and compiled by the user,  they are easy to modify and customize.
* *Open-Source*. Users can study the GSQL implementations to learn by example, and they can develop and submit additions to the library.

== Quick Links

[cols="3,3,3",grid=none,frame=none]

|===
a|
=== xref:centrality-algorithms:index.adoc[Centrality]

Centrality algorithms find the important vertices in a graph based on their connections with other vertices.

* xref:centrality-algorithms:approximate-closeness-centrality.adoc[]
* xref:centrality-algorithms:article-rank.adoc[]
* xref:centrality-algorithms:betweenness-centrality.adoc[]
* xref:centrality-algorithms:closeness-centrality.adoc[]
* xref:centrality-algorithms:degree-centrality.adoc[]
* xref:centrality-algorithms:eigenvector-centrality.adoc[]
* xref:centrality-algorithms:harmonic-centrality.adoc[]
* xref:centrality-algorithms:influence-maximization.adoc[]
* xref:centrality-algorithms:pagerank.adoc[]
* xref:centrality-algorithms:personalized-pagerank.adoc[]
* xref:centrality-algorithms:weighted-degree-centrality.adoc[]
* xref:centrality-algorithms:weighted-pagerank.adoc[]

a|
=== xref:classification-algorithms:index.adoc[Classification]

Classification algorithms label vertices to sort them into various defined classes.

* xref:classification-algorithms:greedy-graph-coloring.adoc[]
* xref:classification-algorithms:k-nearest-neighbors.adoc[]
* xref:classification-algorithms:k-nearest-neighbors-batch.adoc[]
* xref:classification-algorithms:k-nearest-neighbors-cross-validation.adoc[]
* xref:classification-algorithms:maximal-independent-set.adoc[]


a|
=== xref:link-prediction:index.adoc[Link Prediction]

Topological link prediction algorithms determine the closeness of a pair of vertices to make predictions about their relationships.

* xref:link-prediction:adamic-adar.adoc[]
* xref:link-prediction:common-neighbors.adoc[]
* xref:link-prediction:preferential-attachment.adoc[]
* xref:link-prediction:resource-allocation.adoc[]
* xref:link-prediction:same-community.adoc[]
* xref:link-prediction:total-neighbors.adoc[]

|===

[cols="3,3,3",grid=none,frame=none]
|===
a|
=== xref:node-embeddings:index.adoc[Node Embedding]

Node embeddings are vector representations of properties of vertices in a graph.


* xref:node-embeddings:node2vec.adoc[]
* xref:node-embeddings:fast-random-projection.adoc[]
* xref:node-embeddings:weisfeiler-lehman.adoc[]

a|
=== xref:pathfinding-algorithms:index.adoc[Pathfinding]

Pathfinding algorithms find the best path(s) among a set of vertices according to length or cost.

* xref:pathfinding-algorithms:a-star.adoc[]
* xref:pathfinding-algorithms:all-pairs-shortest-path.adoc[]
* xref:pathfinding-algorithms:bfs.adoc[]
* xref:pathfinding-algorithms:cycle-detection.adoc[]
* xref:pathfinding-algorithms:estimated-diameter.adoc[]
* xref:pathfinding-algorithms:max-flow.adoc[]
* xref:pathfinding-algorithms:minimum-spanning-forest.adoc[]
* xref:pathfinding-algorithms:minimum-spanning-tree.adoc[]
* xref:pathfinding-algorithms:single-source-shortest-path-unweighted.adoc[]
* xref:pathfinding-algorithms:single-source-shortest-path-weighted.adoc[]


a|
=== xref:similarity-algorithms:index.adoc[Similarity and Distance]

Similarity algorithms assign a score to a pair of vertices based on how similar they are.
This usually involves seeing if they have the same or similar neighborhoods.

* xref:similarity-algorithms:euclidean.adoc[]
* xref:similarity-algorithms:overlap-similarity.adoc[]
* xref:similarity-algorithms:pearson-similarity.adoc[]
* *Cosine Similarity of Neighborhoods*
** xref:similarity-algorithms:cosine-similarity-of-neighborhoods-batch.adoc[]
** xref:similarity-algorithms:cosine-similarity-of-neighborhoods-single-source.adoc[]
* *Jaccard Similarity of Neighborhoods*
** xref:similarity-algorithms:jaccard-similarity-of-neighborhoods-batch.adoc[]
** xref:similarity-algorithms:jaccard-similarity-of-neighborhoods-single-source.adoc[]
a|

|===



== Library Structure

You can download the library from GitHub: +
https://github.com/tigergraph/gsql-graph-algorithms[https://github.com/tigergraph/gsql-graph-algorithm]

The library contains two folders: `algorithms` and `graphs`.

=== `algorithms`

The `algorithms` folder contains the GSQL implementation of all the graph algorithms offered by the library.
Within the `algorithms` folder are six sub-folders that group the algorithms into six classes:

* *Centrality*
* *Classification*
* *Community*
* *Node Embeddings*
* *Path*
* *Similarity*

Each algorithm has its own subfolder under the category folder.
Inside the algorithm folder, there might be further subfolders depending on whether the GDS Library provides different versions of the algorithm.

[#_graphs]
=== `graphs`

The `graphs` folder contains small sample graphs that you can use to experiment with the algorithms.In this document, we use the test graphs to show you the expected result for each algorithm.The graphs are small enough that you can manually calculate and sometimes intuitively see what the answers should be.

=== Release Branches

Starting with TigerGraph product version 2.6, the GSQL Graph Algorithm Library has release branches:

* *Product version branches* (2.6, 3.0, etc.) are snapshots created shortly after a product version is released.They contain the best version of the graph algorithm library at the time of that product version's initial release.They will not be updated, except to fix bugs.
* *Master branch*: the newest released version.This should be at least as new as the newest.It may contain new or improved algorithms.
* Other branches are development branches.

It is possible to run newer algorithms on an older product version, as long as the algorithm does not rely on features available only in newer product versions.


