= TigerGraph Graph Data Science Library
:page-aliases: intro:overview.adoc

TigerGraph In-Database Graph Data Science (GDS) Library is a collection of more than 50 expertly written, ready-to-use GSQL queries, each of which implements a standard graph or machine learning algorithm.

== Get to know the Graph Data Science (GDS) Library
[.home-card,cols="2,2",grid=none,frame=none]
|===
a|
*Using a Algorithm*

xref:graph-ml:using-an-algorithm:index.adoc[]
page provides information on how to use a TigerGraph Graph Data Science (GDS) Library algorithm.
For more information on the library please see
xref:graph-ml:intro:library-structure.adoc[]
and xref:graph-ml:intro:algorithm-table.adoc[].

a|
*Centrality Algorithms*

xref:graph-ml:centrality-algorithms:index.adoc[]
find the important vertices in a graph based on their connections with other vertices.

a|
*Classification Algorithms*

xref:graph-ml:classification-algorithms:index.adoc[]
label vertices to sort them into various defined classes.

a|
*Community Algorithms*

xref:graph-ml:community-algorithms:index.adoc[]
group together vertices or edges that satisfy some rule for being connected to one another.
a|
*Node Embedding Algorithms*

xref:graph-ml:node-embeddings:index.adoc[]
are vector representations of vertex properties in a graph.

a|
*Pathfinding Algorithms*

xref:graph-ml:pathfinding-algorithms:index.adoc[]
find the best path(s) among a set of vertices according to length or cost.

a|
*Similarity Algorithms*

xref:graph-ml:similarity-algorithms:index.adoc[]
assign a score to a pair of vertices based on how similar they are, usually by referring to their neighborhoods.

a|
*Topological Link Prediction Algorithms*

xref:graph-ml:link-prediction:index.adoc[]
determine the closeness of a pair of vertices to make predictions about their relationships.

a|
|===

GSQL running on the TigerGraph platform is particularly well-suited for graph algorithms for several reasons:

* *Turing-complete* with full support for imperative and procedural programming, ideal for algorithmic computation.
* *Parallel and Distributed Processing,* enabling computations on larger graphs.
* *User-Extensible*. Because the algorithms are written in standard GSQL and compiled by the user,  they are easy to modify and customize.
* *Open-Source*. Users can study the GSQL implementations to learn by example, and they can develop and submit additions to the library.

=== Release Branches

Starting with TigerGraph product version 2.6, the GSQL Graph Algorithm Library has release branches:

* *Product version branches* (2.6, 3.0, etc.) are snapshots created shortly after a product version is released.They contain the best version of the graph algorithm library at the time of that product version's initial release.They will not be updated, except to fix bugs.
* *Master branch*: the newest released version.This should be at least as new as the newest.It may contain new or improved algorithms.
* Other branches are development branches.

It is possible to run newer algorithms on an older product version, as long as the algorithm does not rely on features available only in newer product versions.


