= Using an Algorithm
:description: Instructions on how to use a GDS algorithm.
:experimental:

This page provides information on how to use a TigerGraph Graph Data Science (GDS) Library algorithm.

The algorithm library is included, ready to install, with the TigerGraph database.

== Install/Run on GraphStudio

Nearly all algorithms are available in xref:gui:graphstudio:write-queries.adoc#_create_a_query_or_add_a_query_from_the_algorithm_library[GraphStudio's built-in menu of graph algorithms] that lets you click-to-choose and then install any or all graph algorithms.
For new users on TigerGraph Cloud, this is the simplest way.

== Install/Run as Standard GSQL Queries
Because TigerGraph's graph algorithms are written as GSQL queries, you can install and run them the same way that you install and run other GSQL queries:

* As GSQL commands: `INSTALL QUERY` and `RUN QUERY`
* Using REST endpoints: `POST /gsl/queries/install` and `GET /query/{graph_name}/{query_name}`
* pyTigerGraph functions: `Featurizer.installAlgorithm()` and `Featurizer.runAlgorithm()`
* Using GraphStudio's graphical user interface commands for Add Query, Install Query, and Run Query.

See xref:algorithms-as-gsql-queries.adoc[].

== Install/Run as Packaged Template Queries

Database versions 3.8 and higher offer selected algorithms in an additional format, as packaged template queries.
The packaging simplifies the installation and management of the library, and new CALL command performs just-in-time compilation of the template queries to offer even better performance than before.
TigerGraph is continually improving its library. To get the latest version, users can always go to our GitHub repository: link:https://github.com/tigergraph/gsql-graph-algorithms[GSQL Graph Algorithm Repository].

See xref:packaged-template-algorithms.adoc[].

== Output
Most of the algorithm queries provide multiple output formats.
You usually have the option to output one or more of the following:

* JSON output to console
* CSV output to a file
* Results written to an attribute of vertices or edges

If you are running an algorithm on a TigerGraph Cloud cluster, you need to use AdminPortal to download the algorithm's output files to your local machine.
See xref:gui:admin-portal:gsql-output-file.adoc[] for details.
