= Estimated Diameter

.Supported Graph Characteristics
****
[cols='1']
|===
^|Unweighted edges
^|Directed edges
^|Undirected edges
^|Homogeneous vertex types
^|Heterogeneous vertex types
|===

Algorithm link: link:https://github.com/tigergraph/gsql-graph-algorithms/tree/master/algorithms/Path/estimated_diameter[Estimated Diameter]

****

The diameter of a graph is the worst-case length of a shortest path between any pair of vertices in a graph. It is the farthest distance to travel, to get from one vertex to another, if you always take the shortest path. Finding the diameter requires calculating (the lengths of) all shortest paths, which can be quite slow.

This algorithm uses a simple heuristic to estimate the diameter.
Rather than calculating the distance from each vertex to every other vertex, it selects stem:[K] vertices randomly, where stem:[K] is a user-provided parameter.
It calculates the distances from each of these stem:[K] vertices to all other vertices.
So, instead of calculating stem:[V*(V-1)] distances, this algorithm only calculates stem:[K*(V-1)] distances.
The higher the value of stem:[K], the greater the likelihood of finding the true diameter.

The current version only computes unweighted distances.

== Notes
This algorithm query employs a subquery called *max_BFS_depth*.
Both queries must be installed to run the algorithm.

== Specifications

[source.wrap,gsql]
----
tg_estimate_diameter (SET<STRING> v_type, SET<STRING> e_type, INT seed_set_length,
  BOOL print_accum = TRUE, STRING file_path = "", BOOL display = FALSE)
----

=== Time complexity

This algorithm has a time complexity of stem:[O(k*E)], where stem:[k] is equal to the number of seed vertices and stem:[E] is equal to the number of edges.

=== Result

Returns the single integer that is the estimated diameter of the graph.

=== Parameters

[width="100%",cols="0,1,0",options="header",]
|===
|*Parameter* |Description |Default


|`+SET<STRING> v_type+`
|Names of vertex types to use
|(empty set of strings)

|`+SET<STRING> e_type+`
|Names of edge types to use
|(empty set of strings)

|`INT seed_set_length`
|The number stem:[k] of random seed vertices to use
|10

|`BOOL print_accum`
|If True, output JSON to standard output
|False

|`STRING file_path`
|If not empty, write output to this file
|(empty string)
|===


