= Cosine Similarity
:stem: latex
:experimental:

UDF function: link:https://github.com/tigergraph/gsql-graph-algorithms/tree/277349ce0414ba797edcad1488b6caf1904d5beb/algorithms/Similarity/approximate_nearest_neighbors[Approximate Nearest Neighbors]

Cosine similarity measures the cosine of the angle between two non-zero vectors of an inner product space.

[stem]
++++
\[
\text{Cosine Similarity} = \frac{\sum_{i=1}^{n}A_i \times B_i}{\sqrt{\sum_{i=1}^{n}A_i^2} \times \sqrt{\sum_{i=1}^{n}B_i^2}}
\]
++++

If each entity is being modeled as a set of numerically scored characteristics, than cosine similarity is a commonly used method of measuring the similarity between two entities.

The function operates on vectors formatted as `ListAccum` accumulators.

== Notes

The cosine similarity function is implemented as one option of a multifunction user-defined function (UDF) that is preinstalled in GSQL.

== Specifications

....
tg_similarity_accum(A, B, "COSINE")
....

=== Parameters

[options="header",]
|===
|Name |Description |Data type
|`+A+`
|An n-dimensional vector denoted by a `+ListAccum+` of length `+n+`.
|`+ListAccum<INT/UINT/FLOAT/DOUBLE>+`

|`+B+`
|An n-dimensional vector denoted by a `+ListAccum+` of length `+n+`.
|`+ListAccum<INT/UINT/FLOAT/DOUBLE>+`

| "COSINE"
| A string that identifies the similarity function type.
| `const string`

|===

=== Output

The cosine similarity between the two vectors, which ranges from -1 (exactly opposite) to 1 (exactly the same), with 0 indicating orthogonality.

=== Time complexity

The function has a complexity of stem:[O(n)], where stem:[n] is the number of dimensions of the vectors.

== Example
[tabs]
====
Accum Query::
+
--
[,gsql]
----
CREATE QUERY cosine_similarity_example() FOR GRAPH social {
  ListAccum<INT> @@a = [1, 0, 3];
  ListAccum<INT> @@b = [0, 2, 6];
  double similarity = tg_similarity_accum(@@a, @@b, "COSINE");
  PRINT similarity;
}
----
--
Result::
+
--
[,json]
----
{
    "similarity": 0.868243
}
----
--
====