= Euclidean Distance
:experimental:

Algorithm link: link:https://github.com/tigergraph/gsql-graph-algorithms/tree/277349ce0414ba797edcad1488b6caf1904d5beb/algorithms/Similarity/approximate_nearest_neighbors[Approximate Nearest Neighbors]

Euclidean distance measures the straight line distance between two
points in n-dimensional space. The algorithm takes two vectors denoted
by `ListAccum` and returns the Euclidean distance between them.

== Notes

This algorithm is implemented as a user-defined function. You need to
follow the steps in xref:gsql-ref:querying:func/query-user-defined-functions.adoc[Add a User-Defined Function] to add the
function to GSQL. After adding the function, you can call it in any GSQL
query in the same way as a built-in GSQL function.

== Specifications

....
tg_euclidean_distance_accum(A, B)
....

== Time complexity
The algorithm has a complexity of stem:[O(n)], where stem:[n] is the number of dimensions of the vectors.

== Parameters

[options="header",]
|===
|Name |Description |Data type
|`+A+` |An n-dimensional vector denoted by a `+ListAccum+` of length
`+n+` |`+ListAccum<INT/UINT/FLOAT/DOUBLE>+`

|`+B+` |An n-dimensional vector denoted by a `+ListAccum+` of length
`+n+` |`+ListAccum<INT/UINT/FLOAT/DOUBLE>+`
|===

== Return value

The Euclidean distance between the two vectors.

== Example

[tabs]
====
Query::
+
--
[,gsql]
----
CREATE QUERY euclidean_example() FOR GRAPH social {
  ListAccum<INT> @@a = [1, 2, 3];
  ListAccum<INT> @@b = [4, 5, 6];
  double distance = tg_euclidean_distance_accum(@@a, @@b);
  PRINT distance;
}
----
--
Result::
+
--
[,json]
----
{
    "distance": 5.19615
}
----
--
====