= Similarity Algorithms
:description: Overview of similarity algorithms.

Similarity algorithms assign a score to a pair of vertices based on how similar they are.
This usually involves seeing if they have the same or similar neighborhoods.
This section also includes distance algorithms, as distance is the inverse of similarity.

The TigerGraph Graph Data Science Library provides the following:

== Vector Similarity Functions

[IMPORTANT]
====
The current vector functions are implemented as UDF (User-Defined Functions) and preloaded as part of the Graph Data Science Library.
Unlike other members of the library, they are not GSQL queries.
They are functions which can be used within a query.
====

=== Prerequisites


.To use Vector Similarity Functions please install via one of the two methods below:
* Via TigerGraph CLI run:
+
[source, gsql]
----
tg box algos install <Approximate Nearest Neighbors Algorithm>
----
* Via GSQL terminal run:
+
[source, gsql]
----
GSQL > BEGIN
# Paste <Approximate Nearest Neighbors Algorithm> code after BEGIN command
GSQL > END
GSQL > INSTALL QUERY <Approximate Nearest Neighbors Algorithm>
----

For more information see our public GitHub repo https://github.com/tigergraph/gsql-graph-algorithms/blob/master/algorithms/Similarity/approximate_nearest_neighbors/README.md[Approximate Nearest Neighbors].

=== Function Types
* xref:euclidean.adoc[]  (distance, the inverse of similarity)
* xref:overlap-similarity.adoc[]
* xref:pearson-similarity.adoc[]
* xref:cosine-similarity.adoc[]
* xref:jaccard-similarity.adoc[]

== Vector Similarity of Neighborhoods
=== Cosine Similarity of Neighborhoods
** xref:cosine-similarity-of-neighborhoods-batch.adoc[]
** xref:cosine-similarity-of-neighborhoods-single-source.adoc[]

=== Jaccard Similarity of Neighborhoods
** xref:jaccard-similarity-of-neighborhoods-batch.adoc[]
** xref:jaccard-similarity-of-neighborhoods-single-source.adoc[]

