= Jaccard Similarity
:stem: latex
:experimental:

UDF function: link:https://github.com/tigergraph/gsql-graph-algorithms/tree/277349ce0414ba797edcad1488b6caf1904d5beb/algorithms/Similarity/approximate_nearest_neighbors[Approximate Nearest Neighbors]

Jaccard similarity, also known as the Jaccard index, measures the similarity between finite sample sets.
It is defined as the size of the intersection divided by the size of the union of the sample sets.

[stem]
++++
\[
\text{Jaccard Similarity} = \frac{|A \cap B|}{|A \cup B|} = \frac{\text{cardinality of intersection}}{\text{cardinality of union}}
\]
++++

//The function can accept input as either vectors represented by standard `vector` or `ListAccum`.

The function operates on vectors formatted as `ListAccum` accumulators.


== Notes

The Jaccard Similarity function is implemented as one option of a multifunction user-defined function (UDF) that is preinstalled in GSQL.

== Specifications

....
tg_similarity_accum(A, B, "JACCARD")
....

=== Parameters

[options="header",]
|===
|Name |Description |Data type

|`+A+`
|A `+ListAccum+` representing a set.
|`+ListAccum<T>+`

|`+B+`
|A `+ListAccum+` representing a set.
| `+ListAccum<T>+`

| "JACCARD"
| A string that identifies the similarity function type.
| `const string`
|===

=== Output

The Jaccard similarity between the two sets, calculated as the size of the intersection divided by the size of the union of the sets.

=== Time complexity

The function has a complexity of stem:[O(n log n)], where stem:[n] is the number of dimensions of the vectors, due to the sorting steps involved.

== Example
[tabs]
====
Accum Query::
+
--
[,gsql]
----
CREATE QUERY jaccard_similarity_example() FOR GRAPH social {
  ListAccum<INT> @@a = [1, 2, 3];
  ListAccum<INT> @@b = [2, 3, 4];
  double similarity = tg_similarity_accum(@@a, @@b, "JACCARD");
  PRINT similarity;
}
----
--
Result::
+
--
[,json]
----
{
    "jaccard_similarity": 0.5
}
----
--
====